name: ministero-salute.it-dgc-gateway-client

trigger:
  branches:
    include:
    - master
    - develop
    - feature/*
    - releases/*
pr:
  branches:
    include:
    - master
    - develop
    - releases/*

pool:
  pool: Azure Pipelines

resources:
  containers:
  - container: mongo
    image: mongo
    ports:
    - 27017:27017

services:
  mongo: mongo
 
workspace:
  clean: all

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'JaCoCo'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'SonarQube Azure 8.9'
    scannerMode: 'Other'

- task: SonarQubeAnalyze@4

# - task: SonarQubePublish@4
#   inputs:
#     pollingTimeoutSec: '300'


- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
