version: '3'

networks:
  backend_net:
    driver: bridge

services:
  backend:
    build: .
    image: it-dgc-gateway-client/client
    container_name: it-dgc-gateway-client
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - PROXY_HOST=host
      - PROXY_PORT=8080
      - PROXY_USER=user
      - PROXY_PWD=password
      - MONGO_DB_URI=mongodb://host.docker.internal:27017/DGCDB
      - SIGN_EXTERNAL_URL=https://host/v1/sign
      - SSLDP_JKS_PATH=/security/sslclient/ssldp.jks
      - SSLDP_JKS_PASSWORD=password
      - SSLDP_CERT_PASSWORD=password
      - DGC_BASE_URL=https://acc-dgcg-ws.tech.ec.europa.eu
      - SSLDGC_JKS_PATH=/security/sslclient/ssldgc.jks
      - SSLDGC_JKS_PASSWORD=password
      - SSLDGC_CERT_PASSWORD=password
      - TRUST_JKS_PATH=/security/truststore/truststore.jks
      - TRUST_JKS_PASSWORD=password
      - TRUST_DGC_ANCHOR_ALIAS=anchor_alias
    volumes:
      - ./security/sslclient:/security/sslclient
      - ./security/truststore:/security/truststore
      - ./it-dgc-gateway-client/config:/it-dgc-gateway-client/config
    networks:
      - backend_net