name: Check code style

on:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prettier check
        uses: actionsx/prettier@v2
        with:
          args: --check "**/*.java"
